Error - No uploaded artifact was found!

diff --git a/.github/workflows/build_deploy.yml b/.github/workflows/build_deploy.yml
--- a/.github/workflows/build_deploy.yml
+++ b/.github/workflows/build_deploy.yml
@@ -1,20 +1,12 @@
 #https://jupyterbook.org/en/stable/publish/gh-pages.html
 name: Deploy Jupyter Book
 
-# Run this when the master or main branch changes
 on:
   push:
     branches:
-    - master
-    - docs
-    # If your git repository has the Jupyter Book within some-subfolder next to
-    # unrelated files, you can make this run only if a file within that specific
-    # folder has been modified.
-    #
-    # paths:
-    # - some-subfolder/**
+      - master
+      - docs
 
-# This job installs dependencies, builds the book, and pushes it to `gh-pages`
 jobs:
   deploy-book:
     runs-on: ubuntu-latest
@@ -24,7 +16,6 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    # Install dependencies
     - name: Set up Python 3.11
       uses: actions/setup-python@v4
       with:
@@ -35,28 +26,30 @@ jobs:
         pip install -r docs/requirements.txt 
         pip install sphinxcontrib-mermaid
 
-    # (optional) Cache your executed notebooks between runs
-    # if you have config:
-    # execute:
-    #   execute_notebooks: cache
-    - name: cache executed notebooks
+    - name: Cache executed notebooks
       uses: actions/cache@v3
       with:
         path: docs/_build/.jupyter_cache
-        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}
+        key: jupyter-book-cache-${{ hashFiles('docs/requirements.txt') }}
 
-    # Build the book
     - name: Build the book
       run: |
-        jupyter-book build docs/
+        set -e
+        jupyter-book build docs/ || { echo "Jupyter Book build failed"; exit 1; }
 
-    # Upload the book's HTML as an artifact
+    - name: List contents of build directory
+      run: |
+        ls -lah docs/_build
+        ls -lah docs/_build/html
+
+    - name: Debug build output
+      run: find docs/_build
+
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3.0.1
       with:
         path: "docs/_build/html"
 
-    # Deploy the book's HTML to GitHub Pages
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v2
